
["weapon categories setting"]
	#format: weapon_categories hit_stop_duration speed_ratio camera_shake_duration camera_shake_amplitude
	#example: greatsword 4 0.1 15 2
	#weapon_categories: greatsword, longsword, sword, etc
	#hit_stop_duration: duration of hit stop(tick)
	#speed_ration: percentage rate, 0.0 - 1.0
	#camera_shake_duration: duration of screen shake(tick)
	#camera_shake_amplitude: amplitude of screen shake
	weapon_categories_setting = ["greatsword 5 0.2 7 8", "longsword 3 0.25 10 10", "tachi 4 0.2 8 10", "uchigatana 6 0.2 10 10", "spear 5 0.2 10 10", "trident 3 0.2 10 8", "sword 3 0.45 8 8", "dagger 2 0.6 5 5", "fist 0 0 9 9", "axe 5 0.2 10 10", "legendarysword 9 0.2 15 15", "hardgreatsword 5 0.2 10 10"]

["animation setting"]
	#priority higher than weapon categories setting and override it
	#format: attack_animation hit_stop_duration speed_ratio camera_shake_duration camera_shake_amplitude
	#example: epicfight:biped/combat/greatsword_dash 4 0 20 5
	#attack_animation: modid:path
	#hit_stop_duration: duration of hit stop(tick)
	#speed_ration: percentage rate, 0.0 - 1.0
	#camera_shake_duration: duration of screen shake(tick)
	#camera_shake_amplitude: amplitude of screen shake
	animation_setting = []

["screen shake by guard"]
	#screen shake when guard success
	guard_screen_shake_time = 5
	#Range: 0.0 ~ 10.0
	guard_screen_shake_amplitude = 5.5

["screen shake by advanced guard"]
	#screen shake when advanced guard success, like impactful guard or parry
	advanced_guard_screen_shake_time = 6
	#Range: 0.0 ~ 10.0
	advanced_guard_screen_shake_amplitude = 4.5

["screen shake when guard break"]
	#screen shake when guard break
	guard_break_screen_shake_time = 10
	#Range: 0.0 ~ 10.0
	guard_break_screen_shake_amplitude = 6.0

["disable hit stop"]
	disable_hit_stop = false

