
[general]
	#If true the player mobs will attack all players
	#If false they will ignore players with the same name as themself
	"Attack Twin" = true
	#If the player mobs should be able to open doors.
	"Open Doors" = true
	#The difficulty and above that player mobs can open doors, if enabled above.
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	"Open Doors Difficulty" = "EASY"
	#The chance of the mob getting the ability to pickup items, it's used on mob spawn.
	#Set to -1 to disable.
	#Range: -1.0 ~ 256.0
	"Pickup Item Chance" = 1.0
	#The chance of players dropping a head with their texture.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Player Head Drop Chance" = 0.0
	#The chance of player mobs dropping their head.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Mob Head Drop Chance" = 0.0

#Configs related to spawning the mobs
[spawning]
	#Chance that a player mob will spawn as a baby.
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Baby Spawn Chance" = 0.001
	#The id of the dimensions to block spawning in.
	#The player mobs spawn where Zombies spawn, so no need to block dimensions that doesn't contain Zombies.
	#Example id: "minecraft:overworld"
	"Dimension Blocklist" = []
	#Force the mobs to spawn holding items.
	"Force Items Spawn" = false
	#A list of items that the player mobs can spawn with.
	#Default is 40% for a bow, 10% for a crossbow and 50% for a sword, then the swords are distributed after that.
	#There is a separated chance to spawn with an item at all, this is to pick what to spawn when it does
	#Syntax is "namespace:id-weight"
	"Spawn Items" = ["minecraft:bow-90", "minecraft:crossbow-10", "minecraft:stone_sword-64", "minecraft:iron_sword-20", "minecraft:golden_sword-10", "minecraft:diamond_sword-5", "minecraft:netherite_sword-1"]
	#What item to be able to spawn in the offhand
	#Offhand items can only spawn when on hard difficulty
	#It won't spawn an item in the offhand if it spawns with a bow like item.
	#There is a separated chance to spawn with an item at all, this is to pick what it to spawn when it does
	#Syntax is "namespace:id-weight"
	"Spawn Items Offhand" = ["minecraft:shield-1", "minecraft:air-4"]
	#The difficulty and above that player mobs can spawn with items in their offhand.
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	"Offhand Spawn Difficulty" = "HARD"
	#The chance of items spawning in the offhand
	#If holding a projectile weapon this can spawn a tipped arrow if allowed
	#Else it will spawn from the offhand item list
	#Set to -1 to disable.
	#Range: -1.0 ~ 1.0
	"Offhand Spawn Chance" = 0.5
	#Allow for a change to spawn a random tipped arrow when the mob is holding a projectile weapon
	"Spawn Tipped Arrows" = true
	#A list of potion "namespace:id" to block from getting applied to tipped arrows
	"Tipped Arrow Blocklist" = ["minecraft:awkward", "minecraft:empty", "minecraft:fire_resistance", "minecraft:healing", "minecraft:invisibility", "minecraft:leaping", "minecraft:long_fire_resistance", "minecraft:long_invisibility", "minecraft:long_leaping", "minecraft:long_night_vision", "minecraft:long_regeneration", "minecraft:long_strength", "minecraft:long_swiftness", "minecraft:long_turtle_master", "minecraft:long_water_breathing", "minecraft:luck", "minecraft:mundane", "minecraft:night_vision", "minecraft:regeneration", "minecraft:strength", "minecraft:strong_healing", "minecraft:strong_leaping", "minecraft:strong_regeneration", "minecraft:strong_strength", "minecraft:strong_swiftness", "minecraft:strong_turtle_master", "minecraft:swiftness", "minecraft:thick", "minecraft:turtle_master", "minecraft:water", "minecraft:water_breathing"]

#Configs related to the names of the mobs.
[names]
	#A list of links to get names that the player mobs can have.
	#The names need to be separated by a newline.
	#Names from these links are combined with the named from below
	#As an example you have Twitch subs in the game by using https://whitelist.gorymoon.se
	"Name Links" = []
	#The time interval in minutes when to reload the links (approximately, based on TPS)
	#If set to 0 it will only sync once on load.
	#Range: > 0
	"Reload Interval" = 60
	#A list of names that the player mobs can have.
	"Mob Names" = ["Technoblade", "Darkosto", "016Nojr", "BluSunrize", "Buuz135", "Darkere", "MC_chigoushi", "Polar_bear3525", "Drullkus", "Ellpeck", "Emberwalker", "Jshaman", "Kamefrede", "KnightMiner_", "Lat", "LexManos", "Mrbysco", "P3pp3rF1y", "Pugilist_steve", "Ridanis", "SOTMead", "ShyNieke", "SkySom", "Soaryn", "TamasHenning", "ValkyrieofNight", "XCompWiz", "cpw11", "darkphan", "direwolf20", "dmodoomsirius", "dmodoomsirius", "malte0811", "nekosune", "neptunepink", "vadis365", "wyld", "paulsoaresjr", "Mhykol", "Vswe", "TurkeyDev", "Gen_Deathrow", "Sevadus", "fry_", "luodingaa", "Leavester", "qwzaw", "GGHD223", "LEGO_97", "bokunovl_", "XLhuaji", "MC_miaojiang", "MoYangYMAX", "ShadowK7", "ChunYiLi233", "drzh", "Eternal73512", "UCHIHAHIKARI254", "UchihaHikari", "JackLeeYun", "Old_drinks", "611sama", "maizijun", "Pugilist_Steve", "Livi", "qijidada_", "qjjdedie", "tanfive_knife", "feihebuxia", "vgyfufy", "YY1241YY", "chen", "YangZhang28", "X_Rimuru_X", "Elysia9529", "_Abuyti", "cferrpg", "zhongshen_king", "Ninth_XD", "Sersaph", "BeanBeanBee", "JolliBeeNotJoy", "TheLoki", "aashiba", "5Nekoha_Shizuku", "yuemeng1018", "FengX", "mochenhd", "KevinREL", "yuebeng", "fengiao", "Buff_Strength", "_Floweryoung_", "FPS_killED", "X_AXin_X", "zwwn", "xiaokobe", "Mr_Wei_Qidao", "X_HuazhaWhite_X", "X_HuazhaGreen_X", "X_Shen_Fan_X", "CHpyluochen", "xyxingyu520", "ipeihao", "tianzhangi", "TangZiLuo", "BURNING_WING", "baixiaoyu26", "xiaoshuai520", "Amon103", "QingCourt", "YANG3951", "X_TangGuo_X", "xiaopo122", "yingyuqing", "Saoteman", "____Hu____Tao", "RookieSilver", "FuBoity", "GTASAkakaCJ", "XiaoLv_CH", "8bkingwzms", "xwyuanin", "GHGASL", "LCFop", "JoyBoy521", "Qiqi_Tuer", "Enderxh666", "Yizhi_Tutu", "hurankuangfeng", "Overlap1", "Yu_chengtao1681", "SnowGuest", "RRREE", "Diqry", "me_dinker", "Yu_Chengtao1861", "infinity_AYS", "xuyudemeng", "goudan343428", "Txt_Text", "Xiang_Peach", "GRPQN", "wuxinwuyin", "jian7li73", "Mcaotian", "David43874", "BatataWolf28", "Maple_Ink_Leaf", "WUMING_LOVE416", "zYIHuang", "caibuduolian", "Indooramazing", "jingju", "sanqian0", "zzw123", "Saury0", "NoahsArk3", "Bolin5527", "yjywode", "scaredAxis28478", "wangluoovo", "Oneself_boss", "dorcer", "WUmingogo", "BKAG", "lMinecraft", "YWA_yumi", "MOZeitgeist", "hinamorisaya", "BigDaddy6ix9ine", "Zao_fan", "AlindeT", "wxsg1234567890", "mlkdxt", "K0ngBai2233", "imxiaozhang666", "Geraldddy", "fawn112233", "JiangLing01", "Topaz____", "xiaoyu200592", "denchen09", "MUGEN5", "jiangfeng6666", "luoyeshuoshijie", "Bad_Cat", "TLaiang0218", "WH_09miao", "cheems22", "handsomewubi", "xiaoyao20", "shangyu252", "Baosama", "BenignChunk2219", "Sakurour_Cherry", "Xne1c", "Jabari_is_doing", "Hackerterminator", "Gory_Moon", "Darkosto", "016Nojr", "BluSunrize", "Buuz135", "Darkere", "Darkhax", "Drullkus", "Ellpeck", "Emberwalker", "Gigabit101", "Kamefrede", "KnightMiner_", "Lat", "LexManos", "Mrbysco", "P3pp3rF1y", "Ray", "Ridanis", "SOTMead", "ShyNieke", "SkySom", "Soaryn", "TamasHenning", "ValkyrieofNight", "XCompWiz", "cpw11", "darkphan", "direwolf20", "dmodoomsirius", "dmodoomsirius", "malte0811", "nekosune", "neptunepink", "vadis365", "wyld", "paulsoaresjr", "Mhykol", "Vswe", "TurkeyDev", "Gen_Deathrow", "Sevadus", "fry_"]
	#If the names in the whitelist should be used for the player mobs.
	"Use Whitelist" = true

